name: Validate JSON file

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  validate-json-config:
    strategy:
      matrix:
        environment: ['dev', 'test']
    runs-on: ubuntu-latest
    steps:
      - name: Validate JSON file action
        uses: VOVELEE/validate-json/validate-json-action@main
        with:
          environment: ${{ matrix.environment }}
