name: Validate JSON file

on:
  workflow_dispatch:
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'config/**'

jobs:
  validate-json-config:
    strategy:
      matrix:
        environment: ['dev', 'test']
    runs-on: ubuntu-latest
    steps:
      - name: Validate JSON file action
        uses: VOVELEE/validate-json-action/validate-json@main
        with:
          environment: ${{ matrix.environment }}
