name: Validate JSON file

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Validate JSON file
        shell: pwsh
        